version: '3.8'
services:

  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: database
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - senao-networks
  app:
    build: .
    ports:
      - "80:5000"
    environment:
      - SECRET_KEY=your_secret_key
      - DB_HOST=db
      - DB_PORT=3306
      - DB_NAME=database
      - DB_USER=user
      - DB_PASSWORD=password
    networks:
      - senao-networks
    depends_on:
      - db
    restart: always
volumes:
  db_data:

networks:
  senao-networks:
    driver: bridge